name: Update PDF list

on:
  push:
    paths:
      - 'pdfs/*.pdf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate list.json
        run: |
          python3 .github/scripts/gen_list.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pdfs/list.json
          git commit -m "Auto-update list.json" || echo "No changes to commit"
          git push
